---
title: A Guide for Completing Incorporation Documents for Barbados
author: ''
date: '2019-04-01'
slug: barbados-incorporting-documents-a-guide-for-completion
categories: [Non Data Posts]
tags:
  - Barbados
  
keywords:
  - Barbados
  - Specimen Incorporation Documents
  - CAIPO
---
It took me six months, numerous trips to CAIPO and venting my displeasure to the Deputy Registrar before I was finally successful in incorporating a company last year.
<!--more-->

It took me six months, numerous trips to CAIPO and venting my displeasure to the Deputy Registrar before I was finally successful in incorporating a company last year. The major issue being "errors" in the completion of the documents. Now I would have no complaints about having to correct errors of my making, the problem was that after fixing errors as instructed, new, never before pointed out errors kept being identified. After the experience I decided I would mock up specimens of the forms for anyone else who may be looking to self incorporate. Hopefully it saves you some time and frustration. 

>Disclaimer - 
The specimen documents and points below are based on ones that were approved to incorporate a single director company. They are provided as a guide and should not be used as a substitute for legal advice.


# Required Documents

1. Approved Name Search & Reservation
2. Articles of Incorporation
3. Notice of Directors
4. Notice of Address
5. Attorney Declaration 



# Things To Note    

1. The full name used should be the same on all the documents including the attorney declaration. However Section 5 of the Notice of Directors Form has less character space than the other forms so you should use whatever version of your name fits in there.

2. Do not use abbreviations like "St." or "Ave." in the addresses.

3. Even though it is not stated anywhere you will need to print your name above your signature on the Articles of Incorporation.

4. CAIPO will fill in the dates and the company number. 

# Specimen Documents

The full screen version of the below slide show is available [here](https:/jamaalroach.com/docs_slide.html) or you can download them [here]()




```{r , echo= FALSE}
knitr::include_url('/docs_slide.html', height = "505px")
```

Good luck!


